services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft

    ports:
      - "25565:25565"
      - "24454:24454/udp"

    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "26.2"
      MEMORY: "10G"
      ONLINE_MODE: "FALSE"
      WHITELIST: "FALSE"
      MODS: "/mods"
      WORLD: "/world"

    volumes:
      - minecraft-data:/data
      - ./mods:/mods:ro
      - ./world:/world:ro

    restart: unless-stopped

volumes:
  minecraft-data: